[package]
name = "twir-qotw-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.37", default-features = false }
color-eyre = "0.6.3"
gix = { version = "0.61.0", features = ["blocking-http-transport-reqwest-rust-tls"] }
nom = "7.1.3"
