name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: EmbarkStudios/cargo-deny-action@3f4a782664881cf5725d0ffd23969fcce89fd868 # v1
        with:
          command-arguments: --hide-inclusion-graph

  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Check formating
        run: cargo --locked fmt --check
      - name: Check code style
        run: cargo --locked clippy --all-features --all-targets -- --deny warnings

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install nextest
        uses: taiki-e/install-action@3b0d937160738a7a458c7b13f8b05f08f3f72d80 # v2
        with:
          tool: nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@3b0d937160738a7a458c7b13f8b05f08f3f72d80 # v2
        with:
          tool: cargo-llvm-cov
      - name: Run tests with coverage
        run: cargo --locked llvm-cov nextest
      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        if: success() || failure()
        with:
          name: junit.xml
          path: target/nextest/default/junit.xml
