name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: EmbarkStudios/cargo-deny-action@f87fcad0e65efa7cbdec993036c394fa9be14262 # v2
        with:
          command-arguments: --hide-inclusion-graph

  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check formating
        run: cargo --locked fmt --check
      - name: Check code style
        run: cargo --locked clippy --all-features --all-targets -- --deny warnings

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install nextest
        uses: taiki-e/install-action@5b1c1a554482cdcae4eea02315b6fcdb89dd86fb # v2
        with:
          tool: nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@5b1c1a554482cdcae4eea02315b6fcdb89dd86fb # v2
        with:
          tool: cargo-llvm-cov
      - name: Run tests with coverage
        run: cargo --locked llvm-cov nextest
      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        if: success() || failure()
        with:
          name: junit.xml
          path: target/nextest/default/junit.xml
