name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: EmbarkStudios/cargo-deny-action@34899fc7ba81ca6268d5947a7a16b4649013fea1 # v2
        with:
          command-arguments: --hide-inclusion-graph

  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check formating
        run: cargo --locked fmt --check
      - name: Check code style
        run: cargo --locked clippy --all-features --all-targets -- --deny warnings

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install nextest
        uses: taiki-e/install-action@62730e3d4f6bd81d824694e963e06d7153968c93 # v2
        with:
          tool: nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@62730e3d4f6bd81d824694e963e06d7153968c93 # v2
        with:
          tool: cargo-llvm-cov
      - name: Run tests with coverage
        run: cargo --locked llvm-cov nextest
      - uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        if: success() || failure()
        with:
          name: junit.xml
          path: target/nextest/default/junit.xml
