name: 'JUnit report'

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: junit.xml
        name: 'JUnit report'
        fail-on-error: 'false'
        path: junit.xml
        reporter: java-junit
