name: 'JUnit report'

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'

    steps:
      - name: Report (dorny/test-reporter)
        uses: dorny/test-reporter@v1
        with:
          artifact: junit.xml
          name: 'JUnit report'
          path: junit.xml
          reporter: java-junit

      - name: Download
        uses: dawidd6/action-download-artifact@v3
        with:
          run_id: ${{ github.event.workflow_run.id }}
          path: artifacts
      - name: Report (EnricoMi/publish-unit-test-result-action)
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: artifacts/event/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "artifacts/**/junit.xml"

