name: 'JUnit report'

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          name: junit.xml
          run-id: ${{ github.event.workflow_run.id }}
          path: target/nextest/default/
      - uses: dorny/test-reporter@v1
        with:
          fail-on-error: 'false'
          name: 'JUnit report'
          path: target/nextest/default/junit.xml
          reporter: java-junit
