name: 'JUnit report'

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          name: junit.xml
          run-id: ${{ github.event.workflow_run.id }}
          path: target/nextest/default/
      - uses: dorny/test-reporter@890a17cecf52a379fc869ab770a71657660be727 # v2.1.0
        with:
          fail-on-error: 'false'
          name: 'JUnit report'
          path: target/nextest/default/junit.xml
          reporter: java-junit
